### ISSUE TITLE
Listing DB/migrator/seed definitions in a resource file (or other sources)

### ISSUE THREAD

**Issue by michaelklishin** [juxt/joplin#14]
When using Joplin as a library (e.g. to reset the databases between integration test runs) I find myself
with a bit of DB definition duplication. Perhaps a good way of dealing with it would be some sort of
support for resource files (à la ActiveRecord's `config/database.yml`).

If we want to make things even more flexible, we can create a new protocol for definition loading and
retrieve them from maps, files, and services such as ZooKeeper, etcd, etc.

Any thoughts on this? I'd be happy to contribute this if there's interest in having this in `joplin.core`.

**Comment by martintrojer** [comment]
See https://github.com/weavejester/ragtime/issues/60

**Comment by martintrojer** [comment]
Fixed by #63
