### ISSUE TITLE
ElasticSearch database record should have a key for index name

### ISSUE THREAD

**Issue by michaelklishin** [juxt/joplin#44]
I'd like to use different index names between dev, test, and certainly production environments. I can configure the name with Joplin for JDBC or Cassandra but not ElasticSearch. This means that I have to create ad-hoc ways of detecting the environment in order to name my indices.

If `joplin.elasticsearch.database.ElasticSearchDatabase` allowed specifying an index, I would be able to rely on that.

**Comment by michaelklishin** [comment]
@martintrojer may I ask you to cut a new release with related commits in? Something I'm involved with could use an updated version to eliminate a pretty ugly hack. Thank you!

**Comment by martintrojer** [comment]
@michaelklishin v0.2.5 released

**Comment by michaelklishin** [comment]
Woohoo!
