### ISSUE TITLE
No method in multimethod 'migrate-db' for dispatch value: :sql

### ISSUE THREAD

**Issue by htmfilho** [juxt/joplin#55]
Hello, I'm trying to use Joplin from code but I'm getting the following exception:

IllegalArgumentException No method in multimethod 'migrate-db' for dispatch value: :sql  clojure.lang.MultiFn.getFn (MultiFn.java:160)

I've added joplin.jdbc in my dependencies:

    :dependencies [[org.clojure/clojure "1.6.0" ]
                 [org.clojure/java.jdbc "0.3.6" ]
                 [mysql/mysql-connector-java "5.1.25"]
                 [joplin.core "0.2.9" ]                 
                 [joplin.jdbc "0.2.9" ]]

I wrote datasource.clj as follows:

    (ns jub.datasource
      (:require [clojure.java.jdbc :as jdbc]
                     [joplin.core  :as joplin]
                     [joplin.sql.database]))

    (def mysql-db {:subprotocol "mysql"
                   :subname     "//localhost:3306/jub"
                   :user        "jub_user"
                   :password    "senhas"})

    (def joplin-target {:db {:type :sql 
                        :url (str "jdbc:mysql:" (get mysql-db :subname)
                                  "?user="      (get mysql-db :user)
                                  "&password="  (get mysql-db :password))}
                        :migrator "resources/migrators/sql"})

    (defn migrate-mysql-db []
       (joplin/migrate-db joplin-target))

The readme is not very clear about using joplin from code. It says that I have to load the joplin.core namespace (done) and also the namespaces of the database plugins (I guess joplin.sql.database, but not sure). I've tried to refer the namespaces joplin.jdbc.database and joplin.sql.database, but the error persists.

The code is open source and available in this branch: https://github.com/htmfilho/javaee-utility-belt/tree/Issue%237

Thanks in advance!

**Comment by martintrojer** [comment]
You need to require ' joplin.jdbc.database instead of  'joplin.sql.database

I agree its a bit confusing, and only clear if you read the source.

**Comment by htmfilho** [comment]
Working here! The combination I didn't try ;-) Thanks a lot!
