### ISSUE TITLE
How does Joplin figure out the correct jdbc driver to use?

### ISSUE THREAD

**Issue by htmfilho** [juxt/joplin#57]
I was using Joplin with MySQL, but now I'm moving to SQLite. While using MySQL, Joplin was working perfectly. After changing the configuration to access SQLite the following error occurs:

    CompilerException java.sql.SQLException: No suitable driver found for jdbc:sqlite:db.dub

And then I realized Joplin never asked me for a JDBC driver class for MySQL. How does Joplin figure out the driver and how can I make SQLite's driver visible for it?

https://github.com/EsmerilProgramming/dev-utility-belt/blob/issue%2316/project.clj
https://github.com/EsmerilProgramming/dev-utility-belt/blob/issue%2316/src/jub/datasource.clj

**Comment by michaelklishin** [comment]
Using the schema in the URI.

**Comment by htmfilho** [comment]
Sorry Michael, I didn't get it. Since I've made two questions, is it using the schema in the URL that Joplin figures out the driver or is it using the schema in the URL that makes SQLite's driver visible for Joplin?

Also, the term "Schema" might refer to database schema, but we can also understand it as the format of the URI. I'm not sure we can pass the Driver class in the URI. Could you clarify, please?

**Comment by michaelklishin** [comment]
@htmfilho the database driver is "visible to Joplin" if it's on the JVM classpath. That is managed by Leiningen, or however else you like to manage dependencies. If that's still isn't clear: you must have a dependency specified in `project.clj` and downloaded.

Joplin (actually, clojure.java.jdbc) only needs to know what driver to load and use. You may notice that `jdbc:sqlite:db.dub` has `sqlite` in it and not `mysql`. Please refer to the [clojure.java.jdbc documentation](http://clojure-doc.org/articles/ecosystem/java_jdbc/home.html) to see what URIs for MySQL connections should look like.

>  the term "Schema" might refer to database schema, but we can also understand it as the format of the URI

I said

> the schema in the URI

**Comment by michaelklishin** [comment]
I now see there is a typo. I meant to say the [scheme in the URI](https://tools.ietf.org/html/rfc3986#section-3.1).

**Comment by htmfilho** [comment]
Thanks @michaelklishin 

> the database driver is "visible to Joplin" if it's on the JVM classpath. That is managed by Leiningen,  or however else you like to manage dependencies. If that's still isn't clear: you must have a dependency specified in project.clj and downloaded.

I do have [a dependency in project.clj](https://github.com/EsmerilProgramming/dev-utility-belt/blob/issue%2316/project.clj#L8) and it was downloaded as expected. I even removed it from the .m2 directory to force another download. But, the error persists.

> Joplin (actually, clojure.java.jdbc) only needs to know what driver to load and use. You may notice that jdbc:sqlite:db.dub has sqlite in it and not mysql. Please refer to the clojure.java.jdbc documentation to see what URIs for MySQL connections should look like.

As I said, Joplin is working well with MySQL. I'm not trying to use MySQL. I'm trying to use SQLite, but it doesn't work, producing the mentioned exception. I did recheck [sqlite documentation](https://bitbucket.org/xerial/sqlite-jdbc) to make sure it's correct in [my code](https://github.com/EsmerilProgramming/dev-utility-belt/blob/issue%2316/src/dub/datasource.clj).

Not sure what is wrong in the code below:

    (def joplin-target {:db {:type :sql
                             :url "jdbc:sqlite:db.dub"}
                        :migrator "resources/migrators/sql"})
    
    (defn migrate-db []
       (joplin/migrate-db joplin-target))

    (migrate-db)

It didn't ask for the driver, that's why I'm wondering how it figures it out.

**Comment by htmfilho** [comment]
The problem was solved when I updated the driver version from 3.7.2 to 3.8.7. Thanks for you attention anyway.
