### ISSUE TITLE
Figure out a way to hide passwords

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/joplin#62]
Too many passwords in jdbc urls... It would be great to figure out a way to have them provided elsewhere. Not sure how.

**Comment by martintrojer** [comment]
Has been discussed in various places, this ones are relevant;

* https://github.com/weavejester/ragtime/issues/60
* https://github.com/juxt/joplin/issues/14

**Comment by eric-johnson** [comment]
What about printing passwords? Using Joplin as a library, we can keep our passwords out of our project. Joplin, however, still calls `(println ...)` a lot, which may contain a jdbc url with a password, and may get written to a file.

I'm thinking about replacing calls to println with org.clojure/tools.logging, and then filtering out passwords using a custom log appender.

**Comment by martintrojer** [comment]
similar to #60 

I'm all for replacing the `println`s, if you convince me that we don't introduce any (further) dependency burden on projects that uses joplin as a library.

**Comment by martintrojer** [comment]
Will be fixed by #63
