### ISSUE TITLE
"Could not find environment" on one machine

### ISSUE THREAD

**Issue by sveri** [juxt/joplin#68]
Hi,

I have this project: https://github.com/sveri/mct/tree/ad6d5cc0e84713f3b9e54a8b0c911a535c8c59aa

Now, when I clone it on one machine (where I developed for some time already), I have to create the folder "db" and then run: `lein joplin reset sqlite-dev-env sqlite-dev` it creates the database file as expected.

Now, when I do the same (clone, create "db" run: `lein joplin reset sqlite-dev-env sqlite-dev`) on a different machine I get this error:

    Could not find environment ':sqlite-dev-env'

Not sure what exactly is causing this issue, it is really weird. The code of the project is the same (clean github checkout).

Not working machine:

    lein version
    Leiningen 2.5.2 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
    Windows 8

Working machine: 
    
    Leiningen 2.5.0 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
    Windows 7

So the only obvious difference is the leiningen version and the windows version. Not sure what would cause this -.-

Joplin version used is `0.2.11`

**Comment by sveri** [comment]
And indeed, obvious things are sometimes the cause. I just upgraded to leiningen 2.5.2 on the working machine and now I get the same error:

    Could not find environment ':sqlite-dev-env'

I don't know if it's a bug in leiningen or joplin, but it would be nice if it could be fixed :-)

**Comment by nberger** [comment]
@sveri: Have you tried on leiningen 2.5.1? Would be great to know if it's something specific to 2.5.2 or not.

**Comment by sveri** [comment]
@nberger Yes, I just tried it with 2.5.1 and there it works too, so it must have something to do with 2.5.2.

**Comment by nberger** [comment]
@sveri: FWIW I tracked the issue down to the following commit in leiningen: https://github.com/technomancy/leiningen/commit/4bc49ec5bfd8676e21e497105d6d57b248263d41

I'm not sure how to fix it in joplin 0.2.11 yet, but we can already say that lein tasks in 0.2.11 do not support leinigen 2.5.1

**Comment by nberger** [comment]
@sveri: I have a fix in https://github.com/nberger/joplin/tree/fix-lein-tasks-for-lein-2.5.2. It's based on joplin 0.2.15, it shouldn't be an issue for you to upgrade to that version. If it is, you can easily port the issue back to 0.2.11

@martintrojer: Perhaps it's not the most elegant solution, but it works. Should I open a PR with this fix?  If so, against what branch?

I know, this is for an old version of joplin. But many users still on 0.2.x will be using lein 2.5.2.

**Comment by martintrojer** [comment]
I've created a branch called '0.2'. Please raise a PR against that one

**Comment by sveri** [comment]
@nberger Yea, fixing that in a new version is most probably sufficient for me. Thank you finding the issue.
Apart from that I wonder if this might be a version with leiningen in general. Not knowing anything about the insides I would assume that a minor version update (2.5.1 -> 2.5.2) does not break existing leiningen plugins. Do you have an opinion on that?

**Comment by nberger** [comment]
> Not knowing anything about the insides I would assume that a minor version update (2.5.1 -> 2.5.2) does not break existing leiningen plugins. Do you have an opinion on that?

I agree with you. I suspect no one noted this could be a breaking change: it's for a specific command (lein run) when used with "complex" arguments.  But at the very least, the [leiningen 2.5.2 release announcement](https://devcenter.heroku.com/changelog-items/695) should have had a line about this change.

**Comment by martintrojer** [comment]
released as v0.2.16

**Comment by sveri** [comment]
Hi, just wanted to retest this and found a different unexpected behaviour.

Not sure what exactly causes this, but upgrading to v0.2.16 causes my main function from de.sveri.mct.core to run instead of running the migration.
This happens with leiningen 2.5.x.
I was first suspecting the seed namespace, but commenting that does not fix it and still my server is started.

**Comment by nberger** [comment]
@sveri thanks for checking again. It turns out that my PR introduced 2 (!) new bugs, so the lein tasks are completely broken in 0.2.16 :/

I opened a new PR (#73) fixing both bugs. For this PR I was sure to clean my local leiningen install (tested with 2.5.2-SNAPSHOT in the previous PR, on 2.5.2 and 2.5.1 now) to verify it.

**Comment by martintrojer** [comment]
0.2.17 released

**Comment by sveri** [comment]
Remembers me of my releases from time to time...hey, I got this fixed, *ugh, everything is worse now :D

I just tested 0.2.17 and it works as expected with leiningen 2.5.x. Thank you all for the quick response and fixes, even for the clojuresphere this was at very fast speed :-)

**Comment by nyoung-figly** [comment]
with the release of 2.5.3, this issue has been re-introduced. I think that the fix: `(when (re-find #"^2.5.2" (leiningen-version))` was a little too specific, it probably wants to check if the version is 2.5.2 or greater....

**Comment by sveri** [comment]
Yep...not working with leiningen 2.5.3.

**Comment by featheredtoast** [comment]
I threw something quick at you.

@sveri the PR might be of some interest to you as well, unless there's some other headway that's been done in the past month RE: closp and related projects?
