### ISSUE TITLE
include lein alias code in joplin.core (or repl)?

### ISSUE THREAD

**Issue by martintrojer** [juxt/joplin#71]
Anybody who want to use joplin from the command lein (pun intended) needs to copy some boilerplate from the example project, not very nice.

**Comment by martintrojer** [comment]
2 issues.

* The alias ns needs to know what config to load (need to hoist that into the prohect.clj aliases)?
* The fns in alias calls (System/exit 0) because of cass client (etc)

**Comment by sveri** [comment]
I agree on that. This is a step back from 0.2.x where I could just define some .sql and a project config and run lein migrate env to apply the migration. Would be nice to have that behavior back again.
