### ISSUE TITLE
Unclear docs for adding a new db type

### ISSUE THREAD

**Issue by danielcompton** [juxt/joplin#75]
On https://github.com/juxt/joplin/wiki/Adding-a-new-database-type there is a list of multimethods:

* migrate-db Migrate target database described by a joplin database map.
* ...
* seed-db Migrate target database described by a joplin database map.

It's not clear to me exactly what the difference between migrate-db and seed-db is (apart from the names, and I can make a reasonable guess as to what they'll do). Perhaps these should be updated to be clearer?

**Comment by martintrojer** [comment]
Updated the page.
