### ISSUE TITLE
Migration generation

### ISSUE THREAD

**Issue by rhacker** [juxt/joplin#80]
Is there any helper or a way to generate migration with timestamp within the lib ? Or we have to have our own util script to do it in shell ? 

Thanks

**Comment by martintrojer** [comment]
@rhacker Yes there is create-migration functions.

See example project; https://github.com/juxt/joplin/blob/master/example/src/migrate.clj#L33-L34

**Comment by rhacker** [comment]
oh nice, didn't notice that. Thanks for pointing out :)
