### ISSUE TITLE
Running any joplin repl command always tries to create "ragtime_migrations" table

### ISSUE THREAD

**Issue by andrewoconnor** [juxt/joplin#81]
Whenever I run a command such as create, migrate, seed, etc. the command executes correctly but it seems that it tries to create the "ragtime_migrations" table each command. Is this normal?

example:
=>(def config (load-config "joplin.edn"))
#'test.core/config
=>(reset config :dev :psql-dev)
Rolling back #ragtime.jdbc.SqlDatabase{:db-spec {:connection-uri jdbc:postgresql://127.0.0.1/test?user=postgres}, :migrations-table ragtime_migrations, :url jdbc:postgresql://127.0.0.1/test?user=postgres, :connection-uri jdbc:postgresql://127.0.0.1/test?user=postgres, :db {:type :sql, :url jdbc:postgresql://127.0.0.1/test?user=postgres}, :migrator joplin/migrators/sql, :seed seeds.sql/run}
ERROR:  relation "ragtime_migrations" already exists
STATEMENT:  CREATE TABLE ragtime_migrations (id varchar(255), created_at varchar(32))
Rolling back 20151231232425-create-tests
ERROR:  relation "ragtime_migrations" already exists
STATEMENT:  CREATE TABLE ragtime_migrations (id varchar(255), created_at varchar(32))
Migrating #ragtime.jdbc.SqlDatabase{:db-spec {:connection-uri jdbc:postgresql://127.0.0.1/test?user=postgres}, :migrations-table ragtime_migrations, :url jdbc:postgresql://127.0.0.1/test?user=postgres, :connection-uri jdbc:postgresql://127.0.0.1/test?user=postgres, :db {:type :sql, :url jdbc:postgresql://127.0.0.1/test?user=postgres}, :migrator joplin/migrators/sql, :seed seeds.sql/run}
ERROR:  relation "ragtime_migrations" already exists
STATEMENT:  CREATE TABLE ragtime_migrations (id varchar(255), created_at varchar(32))
Applying 20151231232425-create-tests
ERROR:  relation "ragtime_migrations" already exists
STATEMENT:  CREATE TABLE ragtime_migrations (id varchar(255), created_at varchar(32))
Seeding #ragtime.jdbc.SqlDatabase{:db-spec {:connection-uri jdbc:postgresql://127.0.0.1/test?user=postgres}, :migrations-table ragtime_migrations, :url jdbc:postgresql://127.0.0.1/test?user=postgres, :connection-uri jdbc:postgresql://127.0.0.1/test?user=postgres, :db {:type :sql, :url jdbc:postgresql://127.0.0.1/test?user=postgres}, :migrator joplin/migrators/sql, :seed seeds.sql/run}
ERROR:  relation "ragtime_migrations" already exists
STATEMENT:  CREATE TABLE ragtime_migrations (id varchar(255), created_at varchar(32))
Applying seed function seeds.sql$run@2ba57027
({:id 42, :name "test42"})

my joplin.edn:

`{
    :migrators {
        :sql-mig           "joplin/migrators/sql"
        :sql-mig-extra     "joplin/migrators/sql/extrapath"
    }
    :seeds     {:sql-seed          "seeds.sql/run"}
    :databases {
        :psql-dev       {:type :sql, :url #envf ["jdbc:postgresql://%s/test?user=%s" TARGET_HOST DEV_PGUSER]}
        :psql-prod      {:type :sql, :url #envf ["jdbc:postgresql://psq-prod/prod?user=%s&password=%s" PROD_PGUSER PROD_PGPASSWD]}
    }
    :environments {
        :dev  [{:db :psql-dev, :migrator :sql-mig, :seed :sql-seed}]
        :prod [{:db :sql-prod, :migrator :imported-sql-mig, :seed :imported-sql-seed}]
    }
}`

**Comment by martintrojer** [comment]
@andrewoconnor Yes its normal, this behaviour is inherited from ragtime.jdbc, https://github.com/weavejester/ragtime/blob/master/ragtime.jdbc/src/ragtime/jdbc.clj#L20-L23

**Comment by ohlo** [comment]
this has been fixed in ragtime 0.6.3.

**Comment by martintrojer** [comment]
joplin 0.3.8 uses ragtime 0.6.3

**Comment by ohlo** [comment]
Awesome!
