### ISSUE TITLE
joplin.lein has a hardcoded list of databases and does not allow any others

### ISSUE THREAD

**Issue by danielytics** [juxt/joplin#9]
joplin.lein hardcodes the list of databases and any others are discarded, meaning custom databases won't work with the leiningen plugin.

The temporary solution I've used to allow RethinkDB migrations in my own code is to amend this line https://github.com/juxt/joplin/blob/9b94fad58f695703b981496abf25dfd39643c449/joplin.lein/src/leiningen/joplin.clj#L40 to instead be `(keep (conj libs extra-libs))` where `extra-libs` is `(-> project :joplin :libs)`. Then in my projects project.clj I've added `:libs {:rethinkdb "rethinkdb"}` and now I can use `:type :rethinkdb` in my `:databases` and the driver is loaded from `rethinkdb.database`.

I'm not sure if there is a better solution, but if interested, I can do a pull request. Thoughts?

**Comment by martintrojer** [comment]
Fixed by #63
