### ISSUE TITLE
Upgrade Ragtime to newer version to play well with newer `org.clojure/java.jdbc`

### ISSUE THREAD

**Issue by caleb** [juxt/joplin#91]
Hi,

The version of Ragtime included in joplin at the moment does not play well with the latest `org.clojure/java.jdbc` (version 0.6.1) because it uses a deprecated syntax for `create-table-ddl` that has been removed in `java.jdbc`.

This only causes a problem if you bring in another library that requires this newer version of `org.clojure/java.jdbc` like Conman.

The error is not helpful (cannot turn a Keyword into an ISeq), so if someone pops in here saying they can't migrate their databases with that error, then this might be the reason.

Upgrading my ragtime.core/ragtime.jdbc to 0.6.0 fixed the issue.

Thanks for the work on this library, I love how flexible it is!

Caleb

**Comment by martintrojer** [comment]
joplin 0.3.8 uses ragtime 0.6.3
